service: garden-aid-iot-hub
provider:
  name: aws
  runtime: nodejs4.3
  variableSyntax: '\${{([\s\S]+?)}}' #will be moved to defaults
  iamRoleStatements:
     -  Effect: Allow
        Action:
          - sns:Publish
        Resource: "arn:aws:sns:ap-southeast-2:*:*"

custom: ${{file(./vars-${{opt:stage}}.yml)}}
package:
  include:
    - node_modules
    - src
  exclude:
    - coverage
    - tests
    - .editorconfig
    - .eslintignore
    - .gitignore
    - .synk
    - .travis.yml
    - .create-secrets.js
    - deploy.sh
    - LICENSE
    - package.json
    - README.md

functions:
  checkMoistureLevel:
    handler: index.checkMoistureLevel

resources:
  Resources:
    MoistureData:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: moisture-data-${{opt:stage}}
        AttributeDefinitions:
          -
            AttributeName: ClientId
            AttributeType: S
          -
            AttributeName: Timestamp
            AttributeType: S
        KeySchema:
          -
            AttributeName: ClientId
            KeyType: HASH
          -
            AttributeName: Timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    SensorThing:
      Type: AWS::IoT::Thing
      Properties:
        AttributePayload:
           Attributes:
            SensorType: soil

    # AWS IoT SQL Reference
    # http://docs.aws.amazon.com/iot/latest/developerguide/iot-sql-functions.html
    SensorThingRule:
      Type: AWS::IoT::TopicRule
      Properties:
        TopicRulePayload:
          RuleDisabled: false
          Sql: "SELECT DeviceId, Recorded, Level FROM '${{opt:stage}}/garden/soil/moisture'"
          Actions:
            -
              DynamoDB:
                TableName: { Ref: MoistureData }
                HashKeyField: "ClientId"
                HashKeyValue: "${clientId()}"
                RangeKeyField: "Timestamp"
                RangeKeyValue: "${timestamp()}"
                PayloadField: "Data"
                RoleArn: { Fn::GetAtt: [ IotThingRole, Arn ] }
            -
              Lambda:
                FunctionArn: { Fn::GetAtt: [ checkMoistureLevel, Arn ] }

    SensorThingPolicy:
      Type: AWS::IoT::Policy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: ["iot:Connect"]
              Resource: ["${{custom.sensorThingClientResource}}"]
            - Effect: "Allow"
              Action: ["iot:Publish"]
              Resource: ["${{custom.sensorThingSoilTopicResource}}"]

    SensorPolicyPrincipalAttachmentCert:
      Type: AWS::IoT::PolicyPrincipalAttachment
      Properties:
        PolicyName: { Ref: SensorThingPolicy }
        Principal: ${{custom.iotCertificateArn}}

    SensorThingPrincipalAttachmentCert:
      Type: "AWS::IoT::ThingPrincipalAttachment"
      Properties:
        ThingName: { Ref: SensorThing }
        Principal: ${{custom.iotCertificateArn}}

    IotThingRole:
       Type: AWS::IAM::Role
       Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Principal:
                  Service:
                    - iot.amazonaws.com
                Action:
                  - sts:AssumeRole

    IotThingRolePolicies:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: IotThingRole_Policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: "*"
            -
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
        Roles: [{ Ref: IotThingRole }]

    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: { Fn::GetAtt: [ checkMoistureLevel, Arn ] }
        Action: lambda:InvokeFunction
        Principal: iot.amazonaws.com
