vars:
stages:
    dev:
        vars:
          stageName: dev
          topicPrefix: dev/garden
        regions:
            ap-southeast-2:
                vars:
                    iotCertificateArn: >-
                      arn:aws:iot:ap-southeast-2:686539804960:cert/360ef24b7855e3472db9849797a9afd8e1301cc930989af5a85549fca3ecba5e
                    sensorThingClientResource: >-
                      arn:aws:iot:ap-southeast-2:686539804960:client/${iot:ClientId}
                    sensorThingSoilTopicResource: >-
                      arn:aws:iot:ap-southeast-2:686539804960:topic/dev/garden/soil/moisture
    prod:
        vars:
          stageName: production
          topicPrefix: prod/garden
        regions:
            ap-southeast-2:
                vars:
                    iotCertificateArn: >-
                      arn:aws:iot:ap-southeast-2:686539804960:cert/0cd64913ad26be5f1a1ee9081c8654683a9eeb7815b11477f0b73fcee2158581
                    sensorThingClientResource: >-
                      arn:aws:iot:ap-southeast-2:686539804960:client/${iot:ClientId}
                    sensorThingSoilTopicResource: >-
                      arn:aws:iot:ap-southeast-2:686539804960:topic/prod/garden/soil/moisture
