vars:
stages:
    dev:
        vars:
          stageName: dev
          topicPrefix: dev/garden
        regions:
            ap-southeast-2:
                vars:
                    iotCertificateArn: >-
                      arn:aws:iot:ap-southeast-2:200622725330:cert/9975f3f819ff940873967f80a171257ed77d34ecbdcedcaa33ae8925d6ee0800
                    sensorThingClientResource: >-
                      arn:aws:iot:ap-southeast-2:200622725330:client/${iot:ClientId}
                    sensorThingSoilTopicResource: >-
                      arn:aws:iot:ap-southeast-2:200622725330:topic/dev/garden/soil/moisture
    prod:
        vars:
          stageName: production
          topicPrefix: prod/garden
        regions:
            ap-southeast-2:
                vars:
                    iotCertificateArn: >-
                      arn:aws:iot:ap-southeast-2:200622725330:cert/9ed15f76189cecdfeef979f086f3947e806ca4134acb407084623b16830af757
                    sensorThingClientResource: >-
                      arn:aws:iot:ap-southeast-2:200622725330:client/${iot:ClientId}
                    sensorThingSoilTopicResource: >-
                      arn:aws:iot:ap-southeast-2:200622725330:topic/prod/garden/soil/moisture
